language: ruby
rvm:
- 1.9.3
- 2.0
- jruby-19mode
env:
  matrix:
  - secure: jGRyQRfXC6PL46v0+ITLBVVMP8TguBCUz16CvyDrqWPpe5x7Fey5x2ETbpzMhkOjwpUWVMQ+Kcx/w/bfUyB83SZbepWcrmsqhiJg/WfT/yZ9Bpzk4EA9AUCCCSJrKg0a1vNsXVLJ2wkh0MN8IhrPFk+cIpB5uMjE8SMEazW+gFI=
